# Define all services here - you can have more than one service if required
services:
  devcontainer: # The name of this service with its configuration, must match devcontainer.json
    build: 
      context: .. # Sets the build context at project level, ie. One level above this file
      dockerfile: .devcontainer/Dockerfile
      args: # Define variables that can be used in Dockerfile
        DATA_GROUP: datagrp      # Do NOT change - the group name for shared volume(s) to allow rwx for anyone in this group
        APP_DIR: /workspace/app  # The default directory of your container, must match devcontainer.json
        DATA_DIR: /workspace/data
        REMOTE_USER: vscode      # The name of remote user, must match devcontainer.json
        REMOTE_PASS: G0anna88    # Only do this for development purpose, otherwise could be security issue
    network_mode: "host" # Crucial for vibe coding to talk to host's local llm via localhost
    volumes:
      - ..:/workspace/app        # Must match APP_DIR above
      - datasets:/workspace/data # Must match DATA_DIR above
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

# Non-default volume(s) must be defined here before it can be used in services above
volumes: 
  datasets:        # Name of the volume
    external: true # Indicates that this volume already exists